### PR TITLE
Added basic logging to file

### PR DESCRIPTION
**Pull request by ABeltramo**
We can now monitor log using OSX Console app. 
Logs are saved on ~/Library/Logs/Noti.log

### CODE REVIEW

**Comment by jariz** [comment]
LGTM, but the build crashing is kind of a problem, can you try this suggestion:  
https://travis-ci.org/jariz/Noti/builds/314688720#L45

Basically edit `.travis.yml` to:
```diff
-script: xcodebuild -workspace Noti.xcworkspace -scheme Noti
+script: brew update && xcodebuild -workspace Noti.xcworkspace -scheme Noti
```

**Comment by jariz** [comment]
Looks like it failed again 😞

https://docs.travis-ci.com/user/customizing-the-build/
I think you should use `before_install` instead.
Sorry about this, the CI has been proved to be really valuable in the past so I kind of want to keep it working.

**Comment by ABeltramo** [comment]
Yep np! I'm just super busy at the moment.
I tried to add the command "pod update" but maybe it's correct to "brew update". Will try later!

**Comment by alperenduran** [comment]
Guys Why I received these e-mails?

On 15 Dec 2017, at 01:53, ABeltramo <notifications@github.com<mailto:notifications@github.com>> wrote:


Yep np! I'm just super busy at the moment.
I tried to add the command "pod update" but maybe it's correct to "brew update". Will try later!

**Comment by jariz** [comment]
You're watching this project @alperenduran . Press the unwatch button on the github site.
Also please keep discussion ontopic.

**Comment by jariz** [comment]
Sweet! I'll merge this and release 0.3 later today.
Shame we couldn't really fix #35 but at least we have better debugging now and can ask users to try again and send their logs.

**Pull request merged**
